### ISSUE TITLE
ITVX

### ISSUE THREAD

**Issue by Maverick20256** [imrsaleh/widevineKeys-GUI#1]
Please can you add support for itvx especially 1080p Keys and MPDs from the tv app thanks

also iplayer 1080p and 4k hlg aswel thanks

**Comment by imrsaleh** [comment]
ITVX supported on Generic

**Comment by Maverick20256** [comment]
> ITVX supported on Generic

cant get it to work please help, as itv mpds dont have pssh, and i can only get mpd and license

**Comment by Maverick20256** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="static" mediaPresentationDuration="PT45M23.157333S" maxSegmentDuration="PT7S" minBufferTime="PT10S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period id="1" duration="PT45M23.157333S">
    <BaseURL>dash/</BaseURL>
    <AdaptationSet id="1" group="1" contentType="audio" segmentAlignment="true" audioSamplingRate="48000" mimeType="audio/mp4" codecs="mp4a.40.2" startWithSAP="1">
      <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
      
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="A5B8F873-BF29-46B9-9022-6B2CC9CC17F8">
      </ContentProtection>
      
      <ContentProtection schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <SegmentTemplate timescale="48000" initialization="10-0591-0001-002_22_3_VAR039-HD-S-$RepresentationID$.dash?hdntl=exp=1707253231~acl=%2f10-0591-0001-002%2f*~data=hdntl~hmac=4986bc227efc5c001b4ffd551abe2fdbcd7bb33c7e7e0e0cd9d7383849c36862" media="10-0591-0001-002_22_3_VAR039-HD-S-$RepresentationID$-$Time$.dash?hdntl=exp=1707253231~acl=%2f10-0591-0001-002%2f*~data=hdntl~hmac=4986bc227efc5c001b4ffd551abe2fdbcd7bb33c7e7e0e0cd9d7383849c36862">
        <SegmentTimeline>
          <S t="0" d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="287744" r="2"/>
          <S d="288768"/>
          <S d="246784"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="audio=128000" bandwidth="128000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="2" group="2" contentType="video" par="16:9" minBandwidth="671989" maxBandwidth="8072236" maxWidth="1920" maxHeight="1080" segmentAlignment="true" sar="1:1" frameRate="25" mimeType="video/mp4" startWithSAP="1">
      
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="A5B8F873-BF29-46B9-9022-6B2CC9CC17F8">
      </ContentProtection>
      
      <ContentProtection schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <SegmentTemplate timescale="600" initialization="10-0591-0001-002_22_3_VAR039-HD-S-$RepresentationID$.dash?hdntl=exp=1707253231~acl=%2f10-0591-0001-002%2f*~data=hdntl~hmac=4986bc227efc5c001b4ffd551abe2fdbcd7bb33c7e7e0e0cd9d7383849c36862" media="10-0591-0001-002_22_3_VAR039-HD-S-$RepresentationID$-$Time$.dash?hdntl=exp=1707253231~acl=%2f10-0591-0001-002%2f*~data=hdntl~hmac=4986bc227efc5c001b4ffd551abe2fdbcd7bb33c7e7e0e0cd9d7383849c36862">
        <SegmentTimeline>
          <S t="0" d="3600" r="452"/>
          <S d="3096"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="video=671989" bandwidth="671989" width="704" height="396" codecs="avc1.64001F" scanType="progressive">
      </Representation>
      <Representation id="video=1271975" bandwidth="1271975" width="1024" height="576" codecs="avc1.64001F" scanType="progressive">
      </Representation>
      <Representation id="video=2072036" bandwidth="2072036" width="1024" height="576" codecs="avc1.64001F" scanType="progressive">
      </Representation>
      <Representation id="video=3372029" bandwidth="3372029" width="1280" height="720" codecs="avc1.640028" scanType="progressive">
      </Representation>
      <Representation id="video=5271694" bandwidth="5271694" width="1280" height="720" codecs="avc1.640028" scanType="progressive">
      </Representation>
      <Representation id="video=8072236" bandwidth="8072236" width="1920" height="1080" codecs="avc1.640028" scanType="progressive">
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

**Comment by imrsaleh** [comment]
> > cant get it to work please help, as itv mpds dont have pssh, and i can only get mpd and license

you can find pssh in console if you have EME logger installed with tampermonkey, use filter 'MediaKeySession::generateRequest'

**Comment by Maverick20256** [comment]
> MediaKeySession::generateRequest

doesnt work already tried!!

**Comment by imrsaleh** [comment]
This tool does not extract pssh, you will have to find out for yourself

this issu will be closed
